image: node:9.11
stages:
  - install
  - build
  - staging
  - deploy

app-install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
  only:
    - master
    - production
    - acceptance

app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run build
  only:
    - master
    - production
    - acceptance

# staging
app-staging:
  stage: staging
  image: python:latest
  dependencies:
    - app-build
  script:
    - pip install awscli
    - cd dist/showsourcing
    - aws s3 sync . s3://app-sta.showsourcing.com --delete
  only:
    - master

app-acceptance:
  stage: deploy
  image: python:latest
  dependencies:
    - app-build
  script:
    - pip install awscli
    - cd dist/showsourcing
    - aws s3 sync . s3://app-acc.showsourcing.com --delete
  only:
    - acceptance

app-deploy:
  stage: deploy
  image: python:latest
  dependencies:
    - app-build
  script:
    - pip install awscli
    - cd dist/showsourcing
    - aws s3 sync . s3://app.showsourcing.com --delete
  only:
    - production