image: node:9.11
stages:
  - build
  - staging
  - deploy

app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm install
    - npm run build
  only:
    - master
    - production


app-staging:
  stage: staging
  image: python:latest
  dependencies:
    - app-build
  script:
    - pip install awscli
   - pip install awscli
    - cd dist/showsourcing
    - aws s3 sync . s3://aws-website-showsourcing-web-stagging --delete
  only:
    - master

app-deploy:
  stage: deploy
  image: python:latest
  dependencies:
    - app-build
  script:
    - pip install awscli
    - cd dist/showsourcing
    - aws s3 sync . s3://aws-website-showsourcing-web-dnz2m --delete max-age=3600
  only:
    - production