image: node:9.11
stages:
  - build
  - staging
  - deploy


before_script:
  - npm install

app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run build
  only:
    - master
    - production


app-staging:
  stage: staging
  dependencies:
    - app-build
  script:
    - npm run deploy:staging
  only:
    - master

app-deploy:
  stage: deploy
  dependencies:
    - app-build
  script:
    - npm run deploy:production
  only:
    - production