image: nexusuw/node-8-python-aws-cli
stages:
  - install
  - build
  - staging
  - deploy

app-install:
  stage: install
  script:
    - npm install
    - npm i @angular/cli -g
  artifacts:
    paths:
      - node_modules
  only:
    - supplier-connect
    - development
    - staging


# dev deployment
app-deploy-dev:
  stage: deploy
  script:
    - npm run build --configuration=dev
    - cd dist/showsourcing
    - aws s3 sync . s3://app-dev.showsourcing.com --delete
    - aws s3 cp s3://app-dev.showsourcing.com/index.html s3://app-dev.showsourcing.com/index.html --metadata-directive REPLACE --cache-control max-age=0
  only:
    - supplier-connect
    - development

# sta deployment
app-deploy-sta:
  stage: deploy
  script:
    - npm run build --configuration=sta
    - cd dist/showsourcing
    - aws s3 sync . s3://app-sta.showsourcing.com --delete
    - aws s3 cp s3://app-sta.showsourcing.com/index.html s3://app-sta.showsourcing.com/index.html --metadata-directive REPLACE --cache-control max-age=0
  only:
    - staging