# set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables on bitbucket

image: node:9.11

pipelines:
  default:
    - step:
        script:
          - npm install
          - npm run build --prod
        caches:
          - node
  branches:
    master:
      - step:
          image: node:9.11
          name: Building
          script:
            - npm run install
            - npm run build --prod
          artifacts:
            - ./dist
        
      - step:
          image: atlassian/pipelines-awscli
          name: Deploy to S3
          deployment: staging
          script:
            - cd dist/showsourcing
            - aws s3 sync --delete . s3://aws-website-showsourcing-web-dnz2m
