# set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables on bitbucket

image: node:9.11

pipelines:

  branches:
    master:
      - step:
          image: node:9.11
          name: Building
          script:
            - npm install
            - npm run build --prod
            - npm run build supplier-onboarding --prod
          artifacts:
            - dist/**
          caches:
            - node

      - step:
          image: atlassian/pipelines-awscli
          name: Deploy to S3
          deployment: staging
          script:
            - cd dist/showsourcing
            - aws s3 sync --delete . s3://aws-website-showsourcing-web-dnz2m
            - cd ../supplier-onboarding
            - aws s3 sync --delete . s3://aws-website-supplieronboarding
