import { Entity } from '~core/erm/models/_entity.model';
import { Supplier } from './supplier.model';
import { User } from './user.model';
import { Attachment } from './attachment.model';
import { Category } from './category.model';
import { ExtendedField } from './extended-field.model';
import { AppImage } from './app-image.model';
import { Packaging } from './packaging.model';
import { Price } from './price.model';
import { PriceMatrix } from './price-matrix.model';
import { Project } from './project.model';
import { ProductStatus } from './product-status.model';
import { Tag } from './tag.model';
import { Task } from './task.model';
import { Sample } from './sample.model';
import { ProductVote } from './product-vote.model';
import { Comment } from './comment.model';

export class Product extends Entity<Product> {
	archived ?= false;
	assignee?: User;
	attachments?: Attachment[];
	category?: Category;
	comments?: Comment[];
	description?: string;
	event?: Event;
	extendedFields?: ExtendedField[];
	favorite ?= false;
	harbour?: string;
	images?: AppImage[];
	incoTerm?: string;
	innerCarton?: Packaging;
	lastUpdatedBy?: User;
	leadTimeUnit?: string;
	leadTimeValue?: number;
	masterCarton?: Packaging;
	masterCbm?: number;
	minimumOrderQuantity?: number;
	moqDescription?: string;
	name?: string;
	price?: Price;
	priceMatrix?: PriceMatrix;
	productCount?: number;
	projects?: Project[];
	quantityPer20ft?: number;
	quantityPer40ft?: number;
	quantityPer40ftHC?: number;
	reference?: string;
	sample?: boolean;
	samplePrice?: Price;
	score?: number;
	status?: ProductStatus;
	statushistory?: ProductStatus[];
	supplier?: Supplier;
	tags?: Tag[];
	tasksLinked?: { count: number, items: Task[] };
	samplesLinked?: { count: number, items: Sample[] };
	tasksLinkedAssignedToMe?: { count: number };
	samplesLinkedAssignedToMe?: { count: number };
	tasksLinkedUndone?: { count: number, items: Task[] };
	votes?: ProductVote[];
	__typename ?= 'Product';

}
