// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'us-east-1',
	aws_cognito_identity_pool_id: 'us-east-1:461ba558-89ca-4da2-bd2a-1a8d28f0b6ef',
	aws_cognito_region: 'us-east-1',
	aws_user_pools_id: 'us-east-1_7hoTxMaCf',
	aws_user_pools_web_client_id: '4ppf5o6qlbhr9mmqdtt9p0kkha',
	oauth: {},
	aws_appsync_graphqlEndpoint: 'https://cthuujd7dzdfno6mhynakzlkui.appsync-api.us-east-1.amazonaws.com/graphql',
	aws_appsync_region: 'us-east-1',
	aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
};

export default awsmobile;
