export * from './settings/settings.component';
export * from '../pages/settings-team-members-content/settings-team-members-content.component';
export * from '../pages/settings-company/settings-company-page.component';
export * from '../pages/settings-export/settings-export.component';
export * from '../pages/settings-fields-page/settings-fields-page.component';
export * from '../pages/settings-team-members-invitations/settings-team-members-invitations.component';
export * from '../pages/settings-team-members-page/settings-team-members-page.component';
export * from '../pages/settings-team-members-users/settings-team-members-users.component';
export * from '../pages/settings-workflows-page/settings-workflows-page.component';
