import { Lang } from '../../../API.service';
import { Entity } from './_entity.model';

export class Contact extends Entity<Contact> {
	__typename? = 'Contact';
	id?: string;
	teamId?: string;
	team?: {
		__typename?: 'Team';
		id?: string;
		name?: string;
		ownerUserId?: string;
		owner?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			createdAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		companyId?: string;
		company?: {
			__typename?: 'Company';
			id?: string;
			name?: string;
			ownerUserId?: string;
			createdByUserId?: string;
			createdAt?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		createdByUserId?: string;
		createdBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			createdAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		createdAt?: number;
		lastUpdatedByUserId?: string;
		lastUpdatedBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			createdAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		lastUpdatedAt?: number | null;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	name?: string | null;
	phoneNumber?: string | null;
	email?: string | null;
	jobTitle?: string | null;
	supplierId?: string;
	supplier?: {
		__typename?: 'Supplier';
		id?: string;
		teamId?: string;
		team?: {
			__typename?: 'Team';
			id?: string;
			name?: string;
			ownerUserId?: string;
			companyId?: string;
			createdByUserId?: string;
			createdAt?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		name?: string;
		fullName?: string | null;
		tradingName?: string | null;
		description?: string | null;
		website?: string | null;
		phoneNumber?: string | null;
		country?: string | null;
		city?: string | null;
		address?: string | null;
		officeEmail?: string | null;
		officePhone?: string | null;
		incoTerm?: string | null;
		harbour?: string | null;
		generalMOQ?: number | null;
		generalLeadTime?: number | null;
		favorite?: boolean;
		globalDatabaseId?: string | null;
		archived?: boolean;
		reference?: string | null;
		referenceKey?: number | null;
		createdAt?: number;
		createdByUserId?: string;
		deletedByUSerId?: string | null;
		deletedAt?: number | null;
		lastUpdatedByUserId?: string;
		lastUpdatedAt?: number;
		deleted?: boolean;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	createdAt?: number;
	createdByUserId?: string;
	createdBy?: {
		__typename?: 'User';
		id?: string;
		email?: string;
		firstName?: string;
		lastName?: string;
		phoneNumber?: string | null;
		preferredLanguage?: Lang | null;
		avatar?: string | null;
		createdAt?: number | null;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	deletedByUserId?: string;
	deletedBy?: {
		__typename?: 'User';
		id?: string;
		email?: string;
		firstName?: string;
		lastName?: string;
		phoneNumber?: string | null;
		preferredLanguage?: Lang | null;
		avatar?: string | null;
		createdAt?: number | null;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	deletedAt?: number | null;
	lastUpdatedByUserId?: string;
	lastUpdatedBy?: {
		__typename?: 'User';
		id?: string;
		email?: string;
		firstName?: string;
		lastName?: string;
		phoneNumber?: string | null;
		preferredLanguage?: Lang | null;
		avatar?: string | null;
		createdAt?: number | null;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	lastUpdatedAt?: number;
	deleted?: boolean;
	_version?: number;
	_deleted?: boolean | null;
	_lastChangedAt?: number;
}
