import { Entity } from './_entity.model';
import { Lang, ImageType } from '../../../API.service';

export class Product extends Entity<Product> {
	creationDate ?= Date.now();
	lastUpdatedDate?= Date.now();
	deleted? = false;
	constructor(config?: Product) {
		super(config);
	}
	__typename?: 'Product';
	id?: string;
	teamId?: string;
	team?: {
		__typename?: 'Team';
		id?: string;
		name?: string;
		ownerUserId?: string;
		owner?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		companyId?: string;
		company?: {
			__typename?: 'Company';
			id?: string;
			name?: string;
			ownerUserId?: string;
			createdByUserId?: string;
			createdOn?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedOn?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		createdByUserId?: string;
		createdBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		createdOn?: number;
		lastUpdatedByUserId?: string;
		lastUpdatedBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		lastUpdatedOn?: number | null;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	name?: string;
	supplier?: {
		__typename?: 'Supplier';
		id?: string;
		teamId?: string;
		team?: {
			__typename?: 'Team';
			id?: string;
			name?: string;
			ownerUserId?: string;
			companyId?: string;
			createdByUserId?: string;
			createdOn?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedOn?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		name?: string;
		fullName?: string | null;
		tradingName?: string | null;
		description?: string | null;
		website?: string | null;
		phoneNumber?: string | null;
		country?: string | null;
		city?: string | null;
		address?: string | null;
		officeEmail?: string | null;
		officePhone?: string | null;
		incoTerm?: string | null;
		harbour?: string | null;
		generalMOQ?: number | null;
		generalLeadTime?: number | null;
		favorite?: boolean;
		globalDatabaseId?: string | null;
		archived?: boolean;
		reference?: string | null;
		referenceKey?: number | null;
		creationDate?: number;
		createdByUserId?: string;
		deletedByUSerId?: string | null;
		deletionDate?: number | null;
		lastUpdatedByUserId?: string;
		lastUpdatedDate?: number;
		deleted?: boolean;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	images?: Array<{
		__typename?: 'Image';
		id?: string;
		teamId?: string;
		team?: {
			__typename?: 'Team';
			id?: string;
			name?: string;
			ownerUserId?: string;
			companyId?: string;
			createdByUserId?: string;
			createdOn?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedOn?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		fileName?: string;
		orientation?: number;
		imageType?: ImageType;
		creationDate?: number;
		createdByUserId?: string;
		createdBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		deletedByUserId?: string;
		deletedBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		deletionDate?: number | null;
		lastupdatedByUserId?: string;
		lastUpdatedBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		lastUpdatedDate?: number;
		deleted?: boolean;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null> | null;
	price?: {
		__typename?: 'Price';
		currency?: string | null;
		value?: number | null;
		baseCurrencyValue?: number | null;
	} | null;
	category?: {
		__typename?: 'Category';
		id?: string;
		teamId?: string;
		team?: {
			__typename?: 'Team';
			id?: string;
			name?: string;
			ownerUserId?: string;
			companyId?: string;
			createdByUserId?: string;
			createdOn?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedOn?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		name?: string;
		creationDate?: number;
		createdByUserId?: string;
		createdBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		deletedByUserId?: string;
		deletedBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		deletionDate?: number | null;
		lastupdatedByUserId?: string;
		lastUpdatedBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			creationDate?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		lastUpdatedDate?: number;
		deleted?: boolean;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	description?: string | null;
	favorite?: boolean | null;
	assigneeId?: string;
	assignee?: {
		__typename?: 'User';
		id?: string;
		email?: string;
		firstName?: string;
		lastName?: string;
		phoneNumber?: string | null;
		preferredLanguage?: Lang | null;
		avatar?: string | null;
		creationDate?: number | null;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	minimumOrderQuantity?: number | null;
	moqDescription?: string | null;
	score?: number | null;
	incoTerm?: string | null;
	harbour?: string | null;
	masterCbm?: number | null;
	quantityPer20ft?: number | null;
	quantityPer40ft?: number | null;
	quantityPer40ftHC?: number | null;
	leadTimeValue?: number | null;
	leadTimeUnit?: string | null;
	sample?: boolean | null;
	samplePrice?: {
		__typename?: 'Price';
		currency?: string | null;
		value?: number | null;
		baseCurrencyValue?: number | null;
	} | null;
	archived?: boolean;
	reference?: string | null;
	referenceKey?: number | null;
	createdByUserId?: string;
	deletedByUSerId?: string | null;
	deletionDate?: number | null;
	lastUpdatedByUserId?: string;
	_version?: number;
	_deleted?: boolean | null;
	_lastChangedAt?: number;
}
