import { Entity } from './_entity.model';
import { Lang, ImageType } from '../../../API.service';

export class Task extends Entity<Task> {
	__typename? = 'Task';
	id?: string;
	teamId?: string;
	team?: {
		__typename?: 'Team';
		id?: string;
		name?: string;
		ownerUserId?: string;
		owner?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			createdAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		companyId?: string;
		company?: {
			__typename?: 'Company';
			id?: string;
			name?: string;
			ownerUserId?: string;
			createdByUserId?: string;
			createdAt?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		createdByUserId?: string;
		createdBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			createdAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		};
		createdAt?: number;
		lastUpdatedByUserId?: string;
		lastUpdatedBy?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			createdAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		lastUpdatedAt?: number | null;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	name?: string | null;
	description?: string | null;
	dueDate?: number | null;
	completed?: boolean | null;
	completionDate?: number | null;
	assigneeUserId?: string;
	assignee?: {
		__typename?: 'User';
		id?: string;
		email?: string;
		firstName?: string;
		lastName?: string;
		phoneNumber?: string | null;
		preferredLanguage?: Lang | null;
		avatar?: string | null;
		createdAt?: number | null;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	product?: {
		__typename?: 'Product';
		id?: string;
		teamId?: string;
		team?: {
			__typename?: 'Team';
			id?: string;
			name?: string;
			ownerUserId?: string;
			companyId?: string;
			createdByUserId?: string;
			createdAt?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		name?: string;
		supplier?: {
			__typename?: 'Supplier';
			id?: string;
			teamId?: string;
			name?: string;
			fullName?: string | null;
			tradingName?: string | null;
			description?: string | null;
			website?: string | null;
			phoneNumber?: string | null;
			country?: string | null;
			city?: string | null;
			address?: string | null;
			officeEmail?: string | null;
			officePhone?: string | null;
			incoTerm?: string | null;
			harbour?: string | null;
			generalMOQ?: number | null;
			generalLeadTime?: number | null;
			favorite?: boolean;
			globalDatabaseId?: string | null;
			archived?: boolean;
			reference?: string | null;
			referenceKey?: number | null;
			createdAt?: number;
			createdByUserId?: string;
			deletedByUSerId?: string | null;
			deletedAt?: number | null;
			lastUpdatedByUserId?: string;
			lastUpdatedAt?: number;
			deleted?: boolean;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		images?: Array<{
			__typename?: 'Image';
			id?: string;
			teamId?: string;
			fileName?: string;
			orientation?: number;
			imageType?: ImageType;
			createdAt?: number;
			createdByUserId?: string;
			deletedByUserId?: string;
			deletedAt?: number | null;
			lastupdatedByUserId?: string;
			lastUpdatedAt?: number;
			deleted?: boolean;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null> | null;
		price?: {
			__typename?: 'Price';
			currency?: string | null;
			value?: number | null;
			baseCurrencyValue?: number | null;
		} | null;
		category?: {
			__typename?: 'Category';
			id?: string;
			teamId?: string;
			name?: string;
			createdAt?: number;
			createdByUserId?: string;
			deletedByUserId?: string;
			deletedAt?: number | null;
			lastupdatedByUserId?: string;
			lastUpdatedAt?: number;
			deleted?: boolean;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		description?: string | null;
		favorite?: boolean | null;
		assigneeId?: string;
		assignee?: {
			__typename?: 'User';
			id?: string;
			email?: string;
			firstName?: string;
			lastName?: string;
			phoneNumber?: string | null;
			preferredLanguage?: Lang | null;
			avatar?: string | null;
			createdAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		minimumOrderQuantity?: number | null;
		moqDescription?: string | null;
		score?: number | null;
		incoTerm?: string | null;
		harbour?: string | null;
		masterCbm?: number | null;
		quantityPer20ft?: number | null;
		quantityPer40ft?: number | null;
		quantityPer40ftHC?: number | null;
		leadTimeValue?: number | null;
		leadTimeUnit?: string | null;
		sample?: boolean | null;
		samplePrice?: {
			__typename?: 'Price';
			currency?: string | null;
			value?: number | null;
			baseCurrencyValue?: number | null;
		} | null;
		archived?: boolean;
		reference?: string | null;
		referenceKey?: number | null;
		createdAt?: number;
		createdByUserId?: string;
		deletedByUSerId?: string | null;
		deletedAt?: number | null;
		lastUpdatedByUserId?: string;
		lastUpdatedAt?: number;
		deleted?: boolean;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	supplier?: {
		__typename?: 'Supplier';
		id?: string;
		teamId?: string;
		team?: {
			__typename?: 'Team';
			id?: string;
			name?: string;
			ownerUserId?: string;
			companyId?: string;
			createdByUserId?: string;
			createdAt?: number;
			lastUpdatedByUserId?: string;
			lastUpdatedAt?: number | null;
			_version?: number;
			_deleted?: boolean | null;
			_lastChangedAt?: number;
		} | null;
		name?: string;
		fullName?: string | null;
		tradingName?: string | null;
		description?: string | null;
		website?: string | null;
		phoneNumber?: string | null;
		country?: string | null;
		city?: string | null;
		address?: string | null;
		officeEmail?: string | null;
		officePhone?: string | null;
		incoTerm?: string | null;
		harbour?: string | null;
		generalMOQ?: number | null;
		generalLeadTime?: number | null;
		favorite?: boolean;
		globalDatabaseId?: string | null;
		archived?: boolean;
		reference?: string | null;
		referenceKey?: number | null;
		createdAt?: number;
		createdByUserId?: string;
		deletedByUSerId?: string | null;
		deletedAt?: number | null;
		lastUpdatedByUserId?: string;
		lastUpdatedAt?: number;
		deleted?: boolean;
		_version?: number;
		_deleted?: boolean | null;
		_lastChangedAt?: number;
	} | null;
	reference?: string | null;
	referenceKey?: number | null;
	inProgress?: boolean | null;
	createdAt?: number;
	createdByUserId?: string;
	deletedByUSerId?: string | null;
	deletedAt?: number | null;
	lastUpdatedByUserId?: string;
	lastUpdatedAt?: number;
	deleted?: boolean;
	_version?: number;
	_deleted?: boolean | null;
	_lastChangedAt?: number;
}
