
export type EntityType = 'CATEGORY' | 'EVENT' | 'PRODUCT' | 'REQUEST' | 'EXPORT'
	| 'PROJECT' | 'TASK' | 'SUPPLIER' | 'SAMPLE' | 'USER' | 'TAG' | 'INVITATION';

export enum EntityTypeEnum {
	CATEGORY = 'CATEGORY',
	EVENT = 'EVENT',
	EXPORT = 'EXPORT',
	PRODUCT = 'PRODUCT',
	INVITATION = 'INVITATION',
	REQUEST = 'REQUEST',
	PROJECT = 'PROJECT',
	SUPPLIER = 'SUPPLIER',
	SAMPLE = 'SAMPLE',
	USER = 'USER',
	TASK = 'TASK',
	TAG = 'TAG',
}
