// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fb772f00-63c1-4502-973e-d4ffce0830e6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Alhs8J2La",
    "aws_user_pools_web_client_id": "2ppkv532a1lfgm50c770ldv2qp",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://v64tuju041.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://iwjepoy7zrhj3c7iqccjryin3i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "legacyUserDB-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
