// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
	aws_project_region: 'us-east-1',
	aws_cognito_identity_pool_id: 'us-east-1:9de3e4c8-4442-41e6-9ef4-0983979978d4',
	aws_cognito_region: 'us-east-1',
	aws_user_pools_id: 'us-east-1_Yln6u64bS',
	aws_user_pools_web_client_id: '22b0pi59mouvjc2355qj8p1blq',
	oauth: {},
	aws_dynamodb_all_tables_region: 'us-east-1',
	aws_dynamodb_table_schemas: [
			{
					tableName: 'legacyusers-dev',
					region: 'us-east-1'
			}
	],
	aws_appsync_graphqlEndpoint: 'https://3eplfdokvfb4pbgn4l75fceumu.appsync-api.us-east-1.amazonaws.com/graphql',
	aws_appsync_region: 'us-east-1',
	aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
};
export default awsmobile;
